FROM node:latest as build-stage

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM node:latest as prod-stage

COPY --from=build-stage /app/dist /app
COPY --from=build-stage /app/package.json /app

WORKDIR /app

RUN npm install --prod

EXPOSE 3000

CMD ["node", "./app/main.js"]